config/routes.rb
Phonebook::Application.routes.draw do
  mount Phonebook::API => '/'
  resources :posts

  resources :departments

  resources :employees

  root :to => 'employees#index'

end

app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :name, :ancestry, :parent_id
  has_many :posts
  has_many :employees, :through => :posts
  validates :name, :presence => true, :uniqueness => true
  has_ancestry

  def self.ancestry_options(items, &block)
    return ancestry_options(items){ |i| "#{'---' * i.depth} #{i.name}" } unless block_given?
    result = []
    items.map do |item, sub_items|
      result << [yield(item), item.id]
      result += ancestry_options(sub_items, &block)
    end
    result
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :address, :mobile_phone, :name, :telephone, :post_ids
  validates :name, :mobile_phone, :post_ids, :presence => true
  has_and_belongs_to_many :posts
  has_many :departments, :through => :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :department_id, :name
  validates :name, :department_id, :presence => true
  validates_uniqueness_of :name
  
  has_and_belongs_to_many :employees
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/departments_controller.rb
#encoding:utf-8
class DepartmentsController < ApplicationController
  before_filter :collection_for_parent_select, :except => [:show, :destroy]

  def collection_for_parent_select
    @departments = Department.ancestry_options(Department.scoped.arrange(:order => 'name')) {|i| "#{'---------' * i.depth} #{i.name}" }
  end

  # GET /departments
  # GET /departments.json
  def index

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @departments }
    end
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
    @department = Department.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/new
  # GET /departments/new.json
  def new
    @department = Department.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/1/edit
  def edit
    @department = Department.find(params[:id])
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(params[:department])

    respond_to do |format|
      if @department.save
        format.html { redirect_to departments_path, notice: '新部门添加成功。' }
        format.json { render json: @department, status: :created, location: @department }
      else
        format.html { render action: "new" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /departments/1
  # PUT /departments/1.json
  def update
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to departments_path, notice: '部门信息已更新。' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/employees_controller.rb
#encoding:utf-8
class EmployeesController < ApplicationController
  before_filter :collection_for_post_select, :except => [:index, :show, :destroy]

  def collection_for_post_select
    @posts = Post.all
  end
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.paginate per_page: 20, page: params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_url, notice: '职员添加成功。' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to employees_url, notice: '职员信息更新成功。' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
#encoding:utf-8
class PostsController < ApplicationController
  before_filter :collection_for_parent_select, :except => [:index, :show, :destroy]

  def collection_for_parent_select
    @departments = Department.ancestry_options(Department.scoped.arrange(:order => 'name')) {|i| "#{'------' * i.depth} #{i.name}" }
  end
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate :per_page => 15, :page => params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: '新的职位已创建。' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to posts_url, notice: '职位信息更新成功。' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/departments/_form.html.erb
<% if @department.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= @department.errors.full_messages.join(";") %>
  </div>
<% end %>

<%= form_for(@department, role: "form") do |f| %>
  <div class="form-group">
    <%= f.label :name, "部门名称" %>
    <%= f.text_field :name, class: "form-control", placeholder: "部门名称" %>
  </div>
  <div class="form-group">
    <%= f.label :parent_id, "上级部门" %>
    <%= f.select :parent_id, @departments, {}, {class: "form-control"} %>
  </div>
  <button type="submit" class="btn btn-primary">保存</button>
  <%= link_to '取消', departments_path, class: "btn btn-danger" %>
<% end %>

app/views/departments/edit.html.erb
<h3>编辑<%= @department.name %>部门信息</h3>

<%= render 'form' %>

app/views/departments/index.html.erb
<div>
    <h3 class="page_title">部门管理</h3> 
    <%= link_to '添加新部门', new_department_path, :class => "btn btn-primary new_btn" %>
</div>

<table class="table">
  <tr>
    <th>名称</th>
    <th>操作</th>
  </tr>

  <% @departments.each do |department| %>
    <tr>
      <td><%= department[0] %></td>
      <td width="100px"><%= link_to '编辑', edit_department_path(department[1]) %></td>
    </tr>
  <% end %>
</table>

app/views/departments/new.html.erb
<h3>添加新部门</h3> 

<%= render 'form' %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @department.name %>
</p>


<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>

app/views/employees/_form.html.erb
<% if @employee.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= @employee.errors.full_messages.join(";") %>
  </div>
<% end %>

<%= form_for(@employee, role: "form") do |f| %>
  <div class="form-group">
    <%= f.label :name, "名称" %> <span class="required">*</span>
    <%= f.text_field :name, class: "form-control muted", placeholder: "名称" %>
  </div>
  <div class="form-group">
    <%= f.label :address, "地址" %>
    <%= f.text_field :address, class: "form-control", placeholder: "地址" %>
  </div>
  <div class="form-group">
    <%= f.label :mobile_phone, "手机号码" %> <span class="required">*</span>
    <%= f.text_field :mobile_phone, class: "form-control", placeholder: "手机号码" %>
  </div>
  <div class="form-group">
    <%= f.label :telephone, "固定电话号码" %>
    <%= f.text_field :telephone, class: "form-control", placeholder: "固定电话号码" %>
  </div>
  <div class="form-group">
    <%= f.label :post_ids, "职位" %><br />
    <% @posts.each do |post| %>
      <%= check_box_tag "employee[post_ids][]", post.id, @employee.post_ids.include?(post.id) %>
      <label for="" style="float:none;margin-left:0"><%= post.name%></label>
    <% end %>
  </div>
  <button type="submit" class="btn btn-primary">保存</button>
  <%= link_to '取消', employees_path, class: "btn btn-danger" %>
<% end %>

app/views/employees/edit.html.erb
<h3>编辑<%= @employee.name %>的信息</h3>

<%= render 'form' %>

app/views/employees/index.html.erb
<div>
    <h3 class="page_title">员工管理</h3> 
    <%= link_to '添加员工', new_employee_path, :class => "btn btn-primary new_btn" %>
</div>

<table class="table table-striped">
  <tr>
    <th>姓名</th>
    <th>地址</th>
    <th>移动号码</th>
    <th>固定电话号码</th>
    <th>职务</th>
    <th>部门</th>
    <th>操作</th>
  </tr>

  <% @employees.includes(:posts,:departments).each do |employee| %>
    <tr>
      <td><%= employee.name %></td>
      <td><%= employee.address %></td>
      <td><%= employee.mobile_phone %></td>
      <td><%= employee.telephone %></td>
      <td><%= employee.posts.map(&:name).join(",") %></td>
      <td><%= employee.departments.map(&:name).uniq.join(",") %></td>
      <td><%= link_to '编辑', edit_employee_path(employee) %></td>
    </tr>
  <% end %>
</table>

<%= will_paginate(@employees, :renderer => WillPaginate::ActionView::LinkRenderer) %>

app/views/employees/new.html.erb
<h3>添加新职员</h3>

<%= render 'form' %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @employee.name %>
</p>

<p>
  <b>Address:</b>
  <%= @employee.address %>
</p>

<p>
  <b>Mobile phone:</b>
  <%= @employee.mobile_phone %>
</p>

<p>
  <b>Telephone:</b>
  <%= @employee.telephone %>
</p>

<p>
  <b>Title:</b>
  <%= @employee.title %>
</p>

<p>
  <b>Department:</b>
  <%= @employee.department %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phonebook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-default" id="navbar">
    <div class="navbar-header pull-left">
      <h2 class="logo">PHONEBOOK</h2>
    </div>
	</div>

	<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li><a href="/employees">员工信息管理</a></li>
      <li><a href="/departments">部门管理</a></li>
      <li><a href="/posts">职位管理</a></li>
    </ul>
  </div>

  <div id="page-content-wrapper">
    <% if notice %>
      <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>
	  <%= yield %>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= @post.errors.full_messages.join(";") %>
  </div>
<% end %>

<%= form_for(@post, role: "form") do |f| %>
  <div class="form-group">
    <%= f.label :name, "职位名称" %> <span class="required">*</span>
    <%= f.text_field :name, class: "form-control", placeholder: "职位名称" %>
  </div>
  <div class="form-group">
    <%= f.label :department_id, "隶属部门" %> <span class="required">*</span>
    <%= f.select :department_id, @departments, {}, {class: "form-control"} %>
  </div>
  <button type="submit" class="btn btn-primary">保存</button>
  <%= link_to '取消', posts_path, class: "btn btn-danger" %>
<% end %>

app/views/posts/edit.html.erb
<h3>编辑<%= @post.name %>职位信息</h3>

<%= render 'form' %>

app/views/posts/index.html.erb
<div>
    <h3 class="page_title">职位管理</h3> 
    <%= link_to '添加新职位', new_post_path, :class => "btn btn-primary new_btn" %>
</div>

<table class="table table-striped">
  <tr>
    <th>名称</th>
    <th>所属部门</th>
    <th>操作</th>
  </tr>

  <% @posts.includes(:department).each do |post| %>
    <tr>
      <td><%= post.name %></td>
      <td><%= post.department.name %></td>
      <td><%= link_to '编辑', edit_post_path(post) %></td>
    </tr>
  <% end %>
</table>

<%= will_paginate(@posts, :renderer => WillPaginate::ActionView::LinkRenderer) %>

app/views/posts/new.html.erb
<h3>添加新的职位</h3>

<%= render 'form' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>

<p>
  <b>Department:</b>
  <%= @post.department_id %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>